// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RailsFormInputMultiSelectController from './rails_form_input_multi_select_controller'
application.register("multi_select", RailsFormInputMultiSelectController)
