require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/designers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Designer. As you add validations to Designer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Designer.create! valid_attributes
      get designers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      designer = Designer.create! valid_attributes
      get designer_url(designer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_designer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      designer = Designer.create! valid_attributes
      get edit_designer_url(designer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Designer" do
        expect {
          post designers_url, params: { designer: valid_attributes }
        }.to change(Designer, :count).by(1)
      end

      it "redirects to the created designer" do
        post designers_url, params: { designer: valid_attributes }
        expect(response).to redirect_to(designer_url(Designer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Designer" do
        expect {
          post designers_url, params: { designer: invalid_attributes }
        }.to change(Designer, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post designers_url, params: { designer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested designer" do
        designer = Designer.create! valid_attributes
        patch designer_url(designer), params: { designer: new_attributes }
        designer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the designer" do
        designer = Designer.create! valid_attributes
        patch designer_url(designer), params: { designer: new_attributes }
        designer.reload
        expect(response).to redirect_to(designer_url(designer))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        designer = Designer.create! valid_attributes
        patch designer_url(designer), params: { designer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested designer" do
      designer = Designer.create! valid_attributes
      expect {
        delete designer_url(designer)
      }.to change(Designer, :count).by(-1)
    end

    it "redirects to the designers list" do
      designer = Designer.create! valid_attributes
      delete designer_url(designer)
      expect(response).to redirect_to(designers_url)
    end
  end
end
