require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/source_materials", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SourceMaterial. As you add validations to SourceMaterial, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SourceMaterial.create! valid_attributes
      get source_materials_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      source_material = SourceMaterial.create! valid_attributes
      get source_material_url(source_material)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_source_material_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      source_material = SourceMaterial.create! valid_attributes
      get edit_source_material_url(source_material)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SourceMaterial" do
        expect {
          post source_materials_url, params: { source_material: valid_attributes }
        }.to change(SourceMaterial, :count).by(1)
      end

      it "redirects to the created source_material" do
        post source_materials_url, params: { source_material: valid_attributes }
        expect(response).to redirect_to(source_material_url(SourceMaterial.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SourceMaterial" do
        expect {
          post source_materials_url, params: { source_material: invalid_attributes }
        }.to change(SourceMaterial, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post source_materials_url, params: { source_material: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested source_material" do
        source_material = SourceMaterial.create! valid_attributes
        patch source_material_url(source_material), params: { source_material: new_attributes }
        source_material.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the source_material" do
        source_material = SourceMaterial.create! valid_attributes
        patch source_material_url(source_material), params: { source_material: new_attributes }
        source_material.reload
        expect(response).to redirect_to(source_material_url(source_material))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        source_material = SourceMaterial.create! valid_attributes
        patch source_material_url(source_material), params: { source_material: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested source_material" do
      source_material = SourceMaterial.create! valid_attributes
      expect {
        delete source_material_url(source_material)
      }.to change(SourceMaterial, :count).by(-1)
    end

    it "redirects to the source_materials list" do
      source_material = SourceMaterial.create! valid_attributes
      delete source_material_url(source_material)
      expect(response).to redirect_to(source_materials_url)
    end
  end
end
